openapi: 3.0.0
info:
  title: Rating App API
  version: 1.0.0
paths:
  /api/version:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4etm3f6ijupvksp6g8o
        tag: $latest
      responses:
        '200':
          description: OK
    options:
      x-yc-apigateway-cors:
        allow_origins:
          - "*"
        allow_methods:
          - "GET"
          - "POST"
          - "OPTIONS"
        allow_headers:
          - "Content-Type"
        max_age: 86400

  /api/rate:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4etm3f6ijupvksp6g8o
        tag: $latest
      responses:
        '200':
          description: OK
    options:
      x-yc-apigateway-cors:
        allow_origins:
          - "*"
        allow_methods:
          - "GET"
          - "POST"
          - "OPTIONS"
        allow_headers:
          - "Content-Type"
        max_age: 86400

  /api/ratings:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4etm3f6ijupvksp6g8o
        tag: $latest
      responses:
        '200':
          description: OK
    options:
      x-yc-apigateway-cors:
        allow_origins:
          - "*"
        allow_methods:
          - "GET"
          - "POST"
          - "OPTIONS"
        allow_headers:
          - "Content-Type"
        max_age: 86400

  /health:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4etm3f6ijupvksp6g8o
        tag: $latest
      responses:
        '200':
          description: OK
